### ISSUE TITLE
[Alpha v0.0.7 → vX.X.X] 성능 테스트 

### ISSUE THREAD

**Issue by loosie** [loosie/techdot#29]
### 성능 테스트 진행
- 어느정도 트래픽까지 감당가능한가? (스트레스테스트 목표 설정하기)
- 부하는 발생하지 않는가? (부하테스트 목표 설정하기 - 동접 500명?)

**Comment by loosie** [comment]
---

- 오리지널 요구사항을 만족하는가? ✓
- 논리적으로 올바른가?  
- 쓸데없는 복잡도가 있지는 않은가? 
- Robust한가? (동시성 이슈 처리, 적절한 에러 처리 등)
- 성능이 괜찮은가?  hmm 임계치를 어느정도로 둬야할지 고민이다.
- 안전한가? (ex. SQL Injection 가능한가 등)
- Observable한가? (ex. metrics, logging, tracing 등) 
- 새로 추가된 종속성이 그만한 가치를 하는가? 그들의 라이센스는 수용가능한가? ✓

---

- API는 가능한 만큼 작고 필요한 만큼 큰가?
- 한 개의 작업을 하는데 여러가지 방법 대신 단 한 개의 방법만 있는가?
- 일관성이 있거나, 적어도 놀람 최소화(PLS) 법칙을 따르는가?
- API와 내부함수가 명확히 분리되어있고, 내부가 API에 노출되지 않는가? (not public)
- 사용자 대면(user-facing) 부분에 호환성을 깨는 변경이 있는가? (API 클래스, 설정, 메트릭, 로그 포맷 등) 
- 새 API가 일반적으로 널리 사용가능하고, 쓸데 없이 구체적이지는 않은가?

**Comment by loosie** [comment]
category 캐싱 성능 비교해보기

**Comment by loosie** [comment]
https://loosie.tistory.com/821

**Comment by woon999** [comment]
v X.X.X : 특정 버전이 아닌 계속해서 성능 테스트 진행
